name: Test and Deploy workflow
on: push
jobs:
  linit:
    runs-on: ubuntu-latest
    steps:
      - name: linit
        run: |
          echo "Linting the code..."
          npm linit
  test:
    runs-on: ubuntu-latest
    needs: linit
    steps:
      - name: test
        run: |
          echo "Running tests..."
          npm test
  